spring.application.name=Reverie
spring.datasource.url=jdbc:postgresql://db.wxepynazfltofhyfqaja.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Vasanthi169@Reverie

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect